language: ruby
rvm:
  - 2.1.0
before_install:
- curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
- echo -n $DO_KEY_CHUNK_{0..30} >> ~/.ssh/travisci.pem
- sudo apt-get update
- sudo apt-get install libxml2-dev xz-utils
- chef exec bundle config build.nokogiri --use-system-libraries
- chef exec bundle update
script: chef exec rake ec2