Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
  c.vm.network(:forwarded_port, {:guest=>3389, :host=>3389})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
